/* Companion resources are language-complete and contain no participant or child records. */
let visualTimer=null,visualActive=null;
const visualState={};
function stopVisuals(){if(visualTimer)clearInterval(visualTimer);visualTimer=null;visualActive=null}
function reviewNotice(){return `<div class="review-strip" role="note"><strong>${tx('reviewTitle')}</strong><span>${tx('reviewBanner')}</span></div>`}
function practicalCallout(){return `<section class="practical-callout"><div class="section-label">${tx('practicalEyebrow')}</div><h2>${tx('practicalCallout')}</h2><p>${tx('practicalCalloutText')}</p><a class="button-link" href="#practical">${tx('practicalNav')} <span aria-hidden="true">↗</span></a><p class="micro">${tx('durationNote')}</p></section>`}
function resourcesPage(){return `<div class="eyebrow">${tx('resourcesNav')}</div><h1>${tx('localReadyTitle')}</h1><p class="lead">${tx('localReadyLead')}</p><section class="paper"><h2>${tx('localNoticeTitle')}</h2><p>${tx('localNoticeText')}</p>${EXTRA.localReadiness.map(x=>`<div class="readiness-item"><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></div>`).join('')}</section><section class="paper"><h2>${tx('referenceTitle')}</h2>${(DATA.reference||[]).map(r=>`<details><summary>${esc(r.title)}</summary><div>${blocks(r.blocks)}</div></details>`).join('')}</section><div class="actions"><a href="#contacts">${tx('contactsNav')}</a><a href="#home">${tx('resourcesBack')}</a></div>`}
function blankField(label,wide=false){return `<div class="blank-field ${wide?'wide':''}"><strong>${esc(label)}</strong><span aria-hidden="true"></span></div>`}
function practicalPage(){const p=EXTRA.practical;return `<div class="eyebrow">${tx('practicalEyebrow')}</div><h1>${esc(p.title)}</h1><p class="lead">${tx('practicalLead')}</p><div class="actions no-print"><button id="practical-download">${tx('practicalDownload')}</button><button class="secondary" id="practical-print">${tx('practicalPrint')}</button></div><p id="practical-status" class="micro no-print" role="status"></p><section class="paper practical-document"><div class="print-brand"><img src="assets/brand/inspired-logo-colour.png" alt="Inspired Education" width="164" height="61"></div><h2>${tx('courseTitle')}</h2><p class="micro">${tx('practicalBlank')}<br>${tx('reportVersion')}</p><p>${esc(p.intro)}</p><ul>${p.instructions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="blank-grid">${['staffName','observerName','schoolName','observationDate','policyVersion','observationContext'].map(k=>blankField(tr(k))).join('')}</div><p class="micro">${tx('optionalDetails')}</p>${p.criteria.map(g=>`<section class="observation-group"><h3>${esc(g.area)}</h3>${g.items.map(x=>`<div class="observation-item"><p>${esc(x)}</p><div class="observation-options">${['observed','needsPractice','notObserved'].map(k=>`<span><span class="paper-box" aria-hidden="true"></span>${tx(k)}</span>`).join('')}</div></div>`).join('')}</section>`).join('')}<div class="notes-space"><h3>${tx('evidenceNotes')}</h3><div class="writing-lines"></div></div><div class="notes-space"><h3>${tx('actionPlan')}</h3><div class="writing-lines"></div></div><h3>${tx('outcome')}</h3>${p.decisionOptions.map(x=>`<p><span class="paper-box" aria-hidden="true"></span> ${esc(x)}</p>`).join('')}<div class="blank-grid">${['staffSignature','observerSignature','reviewDate'].map(k=>blankField(tr(k))).join('')}</div><p>${esc(p.footer)}</p><p class="micro"><strong>${tx('checklistDisclaimer')}</strong></p></section>`}
/* Abstract icons only: no bodies, exposed children, or unverified clinical manoeuvres. */
const iconPaths={
 plan:'<rect x="25" y="18" width="50" height="65" rx="7"/><path d="M40 18v-5h20v5M37 38h28M37 51h28M37 64h18"/>',
 supplies:'<path d="M18 45h64v38H18zM27 45V31h46v14M35 31V21h30v10M28 58h44M39 71h22"/>',
 hands:'<path d="M30 73c-8-8-11-23-3-25l9 9V27c0-8 10-8 10 0v22-29c0-8 10-8 10 0v29-22c0-8 10-8 10 0v27-13c0-8 10-8 10 0v24c0 18-14 25-26 25-9 0-14-7-20-17z"/>',
 support:'<path d="M22 23h56v42H51L33 80V65H22z"/><path d="M38 44h24M50 32v24"/>',
 clean:'<rect x="23" y="25" width="54" height="54" rx="7"/><path d="M35 51l10 10 22-25M76 12v14M69 19h14M17 78v14M10 85h14"/>',
 bin:'<path d="M27 31h46l-5 52H32zM22 31h56M40 31V20h20v11M43 42v28M57 42v28"/>',
 repeat:'<path d="M25 42a28 28 0 0 1 49-11M74 16v18H57M75 59a28 28 0 0 1-49 11M26 85V67h17"/>',
 voice:'<path d="M17 20h66v42H46L28 80V62H17z"/><path d="M30 36h38M30 48h25"/>',
 pause:'<rect x="27" y="20" width="16" height="63" rx="5"/><rect x="57" y="20" width="16" height="63" rx="5"/>',
 choice:'<path d="M20 28h60v50H20zM30 41l5 5 8-10M49 41h18M30 62l5 5 8-10M49 62h18"/>',
 listen:'<path d="M30 47c-7-38 49-39 44-3-2 18-19 14-20 31-1 16-22 14-23 2M42 44c-3-17 21-18 21-1 0 9-12 8-12 20"/>'
};
function visualIcon(name){name=({people:'support',station:'supplies',zones:'clean',speech:'voice',contain:'bin',stop:'pause',reset:'repeat',notice:'listen'})[name]||name;return `<svg viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${iconPaths[name]||iconPaths.plan}</svg>`}
function guideIcons(id){return id==='prepare'?['plan','supplies','clean','hands','support','choice']:id==='sequence'?['clean','bin','hands','supplies','repeat','hands']:['voice','listen','pause','choice','support','voice']}
function visualGuides(n){return EXTRA.visualGuides.filter(g=>g.module===n).map(g=>{const i=Math.min(visualState[g.id]||0,g.steps.length-1),step=g.steps[i];return `<section class="visual-guide" data-visual="${esc(g.id)}" aria-label="${esc(g.title)}"><div class="section-label">${tx('visualLabel')}</div><h2>${esc(g.title)}</h2><p>${esc(g.intro)}</p><div class="visual-scene" role="img" aria-label="${esc(step.title)}">${g.steps.map((s,j)=>`<div class="visual-object ${i===j?'active':''}" data-stage="${j}"><span>${String(j+1).padStart(2,'0')}</span>${visualIcon(s.icon||guideIcons(g.id)[j%6])}</div>`).join('<span class="visual-arrow" aria-hidden="true">→</span>')}</div><div class="visual-caption" aria-live="polite" aria-atomic="true"><div class="section-label" data-visual-count>${tx('stepCount',{n:i+1,total:g.steps.length})}</div><h3 data-visual-title>${esc(step.title)}</h3><p data-visual-text>${esc(step.text)}</p></div><div class="visual-controls"><button data-visual-play="${esc(g.id)}" aria-pressed="false">${tx('play')}</button><button class="secondary" data-visual-prev="${esc(g.id)}" ${i===0?'disabled':''}>${tx('previousStep')}</button><button class="secondary" data-visual-next="${esc(g.id)}" ${i===g.steps.length-1?'disabled':''}>${tx('nextStep')}</button><button class="text-button" data-visual-restart="${esc(g.id)}">${tx('restart')}</button></div><p class="micro visual-warning">${tx('visualCaveat')}</p><details><summary>${tx('transcript')}</summary><div class="visual-transcript">${g.transcript?`<p>${plain(g.transcript)}</p>`:g.steps.map(s=>`<h3>${esc(s.title)}</h3><p>${esc(s.text)}</p>`).join('')}</div></details></section>`}).join('')}
function showVisual(id,index){const g=EXTRA.visualGuides.find(x=>x.id===id),el=document.querySelector(`[data-visual="${id}"]`);if(!g||!el)return;index=Math.max(0,Math.min(index,g.steps.length-1));visualState[id]=index;el.querySelectorAll('[data-stage]').forEach((x,i)=>x.classList.toggle('active',i===index));el.querySelector('.visual-scene').setAttribute('aria-label',g.steps[index].title);el.querySelector('[data-visual-count]').textContent=tr('stepCount',{n:index+1,total:g.steps.length});el.querySelector('[data-visual-title]').textContent=g.steps[index].title;el.querySelector('[data-visual-text]').textContent=g.steps[index].text;el.querySelector('[data-visual-prev]').disabled=index===0;el.querySelector('[data-visual-next]').disabled=index===g.steps.length-1}
function updatePlayButtons(){document.querySelectorAll('[data-visual-play]').forEach(x=>{const playing=x.dataset.visualPlay===visualActive;x.textContent=tr(playing?'pause':'play');x.setAttribute('aria-pressed',String(playing));x.closest('.visual-guide').classList.toggle('playing',playing)})}
function pauseVisual(){stopVisuals();updatePlayButtons()}
function bindExtras(){document.querySelectorAll('[data-visual-play]').forEach(b=>b.onclick=()=>{const id=b.dataset.visualPlay;if(visualActive===id)return pauseVisual();stopVisuals();const g=EXTRA.visualGuides.find(x=>x.id===id);if((visualState[id]||0)===g.steps.length-1)showVisual(id,0);visualActive=id;updatePlayButtons();visualTimer=setInterval(()=>{const next=(visualState[id]||0)+1;if(next>=g.steps.length){pauseVisual();return}showVisual(id,next)},6000)});for(const [attr,delta]of[['prev',-1],['next',1],['restart',null]])document.querySelectorAll(`[data-visual-${attr}]`).forEach(b=>b.onclick=()=>{pauseVisual();const id=b.dataset['visual'+attr[0].toUpperCase()+attr.slice(1)];showVisual(id,delta===null?0:(visualState[id]||0)+delta)});const print=$('#practical-print');if(print)print.onclick=()=>window.print();const download=$('#practical-download');if(download)download.onclick=async()=>{const lang=state.language;download.disabled=true;download.textContent=tr('preparingPdf',{},lang);try{const bytes=await makePracticalPDF(lang);saveBlob(new Blob([bytes],{type:'application/pdf'}),tr('practicalFilename',{},lang),'#practical-status',tr('fileReady',{},lang),lang)}catch(e){notify(tr('pdfError',{},lang))}finally{download.disabled=false;download.textContent=tr('practicalDownload',{},lang)}}}
/* Each PDF page is drawn with bundled fonts; this preserves French and Kreol characters. */
async function makePracticalPDF(lang=state.language){await document.fonts?.ready;const p=window.COURSE_EXTRAS[lang].practical,t=(k)=>tr(k,{},lang),{PDFDocument}=window.PDFLib,doc=await PDFDocument.create(),logo=await certificateLogo();doc.setTitle(t('courseTitle')+' - '+t('practicalNav'));doc.setAuthor('Inspired Education');doc.setLanguage(locale(lang));doc.setSubject(t('checklistDisclaimer'));let canvas,ctx,y,pageNumber=0;const images=[],W=1240,H=1754,L=80,R=1160;
function freshPage(){if(canvas)images.push(canvas.toDataURL('image/png'));canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);ctx.fillStyle='#122147';ctx.fillRect(0,0,W,16);if(logo)ctx.drawImage(logo,L,40,220,81);ctx.font='20px Open Sans';ctx.fillStyle='#415165';ctx.textAlign='right';ctx.fillText(t('courseLine1')+' · 1.0',R,80);ctx.textAlign='left';pageNumber++;ctx.fillText(String(pageNumber),R-15,H-45);let footerSize=16;while(footerSize>10){ctx.font=footerSize+'px Open Sans';if(ctx.measureText(t('practicalBlank')).width<R-L-45)break;footerSize--}ctx.fillText(t('practicalBlank'),L,H-45);y=158;}
function need(h){if(y+h>H-100)freshPage()}
function lines(text,size=22,width=R-L,bold=false){ctx.font=`${bold?'600 ':''}${size}px Open Sans`;const result=[];for(const para of String(text).split('\n')){let line='';for(const word of para.split(/\s+/)){const test=line?line+' '+word:word;if(ctx.measureText(test).width>width&&line){result.push(line);line=word}else line=test}result.push(line)}return result}
function write(text,size=22,bold=false,after=15){const ls=lines(text,size,R-L,bold),lineH=Math.ceil(size*1.46);for(const line of ls){need(lineH);ctx.font=`${bold?'600 ':''}${size}px Open Sans`;ctx.fillStyle=bold?'#122147':'#25364a';ctx.fillText(line,L,y+size);y+=lineH}y+=after}
function field(label){need(83);write(label,19,true,4);ctx.strokeStyle='#b4c0ce';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(L,y+27);ctx.lineTo(R,y+27);ctx.stroke();y+=52}
function options(labels){const widths=labels.map(a=>ctx.measureText(a).width+48),spacing=24;let x=L;ctx.font='18px Open Sans';for(const label of labels){const width=ctx.measureText(label).width+48;if(x+width>R){x=L;y+=34}ctx.strokeStyle='#526174';ctx.lineWidth=1.4;ctx.strokeRect(x,y+2,19,19);ctx.fillStyle='#415165';ctx.fillText(label,x+28,y+18);x+=width+spacing}y+=38}
freshPage();write(p.title,34,true,20);write(t('reportVersion'),18,false,15);write(t('reviewBanner'),20,true,15);if(lang!=='en')write(t('translationReviewNotice'),19,false,15);write(p.intro,22,false,15);for(const instruction of p.instructions)write('• '+instruction,21,false,10);for(const key of ['staffName','observerName','schoolName','observationDate','policyVersion','observationContext'])field(t(key));write(t('optionalDetails'),18,false,10);
for(const group of p.criteria){need(155);write(group.area,27,true,17);for(const item of group.items){need(lines(item,21).length*31+75);write(item,21,false,7);options(['observed','needsPractice','notObserved'].map(t));ctx.strokeStyle='#e0e6ee';ctx.beginPath();ctx.moveTo(L,y);ctx.lineTo(R,y);ctx.stroke();y+=18}}
for(const key of ['evidenceNotes','actionPlan']){need(210);write(t(key),24,true,18);for(let i=0;i<4;i++){ctx.strokeStyle='#cbd3dd';ctx.beginPath();ctx.moveTo(L,y+20);ctx.lineTo(R,y+20);ctx.stroke();y+=35}y+=14}need(150);write(t('outcome'),25,true);for(const option of p.decisionOptions){need(lines(option,21).length*31+36);ctx.strokeStyle='#526174';ctx.strokeRect(L,y+6,19,19);const ls=lines(option,21,R-L-35);for(const [i,line] of ls.entries()){ctx.font='21px Open Sans';ctx.fillStyle='#25364a';ctx.fillText(line,L+34,y+21+i*31)}y+=ls.length*31+16}for(const key of ['staffSignature','observerSignature','reviewDate'])field(t(key));write(p.footer,20,false);write(t('checklistDisclaimer'),19,true);images.push(canvas.toDataURL('image/png'));for(const img of images){const png=await doc.embedPng(img),page=doc.addPage([595.28,841.89]);page.drawImage(png,{x:0,y:0,width:595.28,height:841.89})}return doc.save()}
