const fs=require('fs'),vm=require('vm');const {webcrypto}=require('crypto');
const base=require('path').resolve(__dirname,'..')+'/';
function makeHarness(seed=null,options={}){
 const nodes={},store={...(options.storage||{})},writes=[],objectURLs=[];if(seed!==null){let value=seed;if(!options.rawSeed&&value&&typeof value==='object'&&!Array.isArray(value)&&options.seedKey!=='inspired-co-regulation-v1')value={version:'1.1',...value};store[options.seedKey||'inspired-co-regulation-v1.1']=options.rawSeed?value:JSON.stringify(value)}
 const element=(key)=>({key,innerHTML:'',textContent:'',style:{},value:'',checked:false,attributes:{},children:[],dataset:{},setAttribute(k,v){this.attributes[k]=v},getAttribute(k){return this.attributes[k]},focus(){this.focused=true},scrollIntoView(){},click(){this.clicked=true},showModal(){this.open=true},close(){this.open=false},appendChild(child){this.children.push(child);child.parentNode=this;return child},remove(){if(this.parentNode)this.parentNode.children=this.parentNode.children.filter(n=>n!==this)}});const node=key=>nodes[key]??=element(key);
 const ctx={console,crypto:webcrypto,Blob,TextEncoder,Uint8Array,ArrayBuffer,atob,btoa,setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},scrollY:0,scrollTo(){},matchMedia:()=>({matches:false,addEventListener(){}}),URL:{createObjectURL:()=>{const u='blob:qa-'+(objectURLs.length+1);objectURLs.push(u);return u},revokeObjectURL(){}},location:{hash:'#home'},localStorage:{getItem:k=>{if(options.storageReadError)throw Error('Storage unavailable');return store[k]??null},setItem:(k,v)=>{writes.push([k,v]);if(options.storageWriteError)throw Error('Storage quota exceeded');store[k]=v},removeItem:k=>{throw Error('Unexpected storage deletion: '+k)}},document:{documentElement:{},querySelector:node,querySelectorAll:()=>[],createElement:element,fonts:{ready:Promise.resolve()},body:element('body')},window:null};ctx.window=ctx;ctx.addEventListener=()=>{};ctx.print=()=>{};vm.createContext(ctx);
 let scripts=[...fs.readFileSync(base+'index.html','utf8').matchAll(/<script[^>]+src="([^"]+)"/g)].map(x=>x[1].split(/[?#]/)[0]).filter(x=>!x.startsWith('vendor/'));
 for(const f of scripts.filter(f=>!options.englishOnly||!['course-data-fr.js','course-data-mfe.js'].includes(f))){if(f==='app.js'&&options.beforeApp)options.beforeApp(ctx);vm.runInContext(fs.readFileSync(base+f,'utf8'),ctx,{filename:f})}
 return{ctx,nodes,store,writes,node,element,run:s=>vm.runInContext(s,ctx)};
}
module.exports={makeHarness,base};
