/* Run with node tools/test-course.cjs after python3 tools/assemble.py. */
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),ctx={window:{}};vm.createContext(ctx);
for(const f of ['course-data.js','course-data-fr.js','course-data-mfe.js','i18n.js','course-extras.js'])vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx,{filename:f});
const data=ctx.window,plain=v=>JSON.parse(JSON.stringify(v));let count=0;
const check=(name,fn)=>{fn();count++;console.log('PASS '+name)};
for(const [lang,key]of [['en','COURSE'],['fr','COURSE_FR'],['mfe','COURSE_MFE']]){
 const c=plain(data[key]),u=plain(data.COURSE_UI[lang]),e=plain(data.COURSE_EXTRAS[lang]);
 check(lang+' generated dictionaries match sources',()=>{for(const [name,v]of [['course',c],['ui',u],['course-extras',e]])assert.deepEqual(v,JSON.parse(fs.readFileSync(path.join(root,`${name}-${lang}.json`),'utf8')))});
 check(lang+' module and reflection topology',()=>{assert.deepEqual(c.modules.map(m=>m.id),[1,2,3,4,5,6]);for(const [i,m]of c.modules.entries()){assert.equal(m.pages.length,2);for(const [j,p]of m.pages.entries())assert.deepEqual(p.blocks.map(b=>b.type),plain(data.COURSE.modules[i].pages[j].blocks.map(b=>b.type)));assert.ok(m.pages[0].blocks.every(b=>b.text.trim().length));assert.ok(m.pages[1].blocks.length>=8)}});
 check(lang+' quiz keys and safety gates',()=>{assert.equal(c.questions.length,20);assert.deepEqual(c.questions.map(q=>q.answer),plain(data.COURSE.questions.map(q=>q.answer)));assert.deepEqual(c.questions.flatMap((q,i)=>q.critical?[i+1]:[]),[6,9,10,11,12,18]);for(const q of c.questions){assert.equal(q.options.length,4);assert.ok(q.options[q.answer]&&q.why)}});
 check(lang+' quick checks, timing and visuals',()=>{assert.equal(e.practice.length,6);assert.deepEqual(e.practice.map(q=>q.a),plain(data.COURSE_EXTRAS.en.practice.map(q=>q.a)));assert.equal(e.meta.reduce((n,m)=>n+m.time,0),48);assert.equal(e.visualGuides.length,3);assert.deepEqual(e.visualGuides.map(g=>g.id),plain(data.COURSE_EXTRAS.en.visualGuides.map(g=>g.id)));for(const g of e.visualGuides){assert.ok(g.steps.length>=5);assert.ok(g.steps.every(s=>s.title&&s.text&&s.icon))}});
 check(lang+' UI keys, placeholders and external resources',()=>{assert.deepEqual(Object.keys(u).sort(),Object.keys(data.COURSE_UI.en).sort());for(const k of Object.keys(u))if(typeof u[k]==='string')assert.deepEqual((u[k].match(/\{\w+\}/g)||[]).sort(),(data.COURSE_UI.en[k].match(/\{\w+\}/g)||[]).sort(),k);assert.equal(e.videos.length,3);for(const name of ['videos','sources']){assert.deepEqual(e[name].map(x=>x.url),plain(data.COURSE_EXTRAS.en[name].map(x=>x.url)));assert.ok(e[name].every(x=>x.url.startsWith('https://')))}});
}
check('all runtime resources exist locally',()=>{const html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const [,src]of html.matchAll(/(?:src|href)="([^"]+)"/g)){if(!src.startsWith('#'))assert.ok(fs.existsSync(path.join(root,src)),src)}});
check('separate local data and no automatic transmission',()=>{const app=fs.readFileSync(path.join(root,'app.js'),'utf8'),cert=fs.readFileSync(path.join(root,'certificate.js'),'utf8');assert.ok(app.includes("KEY='inspired-co-regulation-v1'"));assert.ok(cert.includes('CR-ONLINE-'));assert.ok(cert.includes('X-Unsent: 1'));assert.doesNotMatch(app+cert,/fetch\(|XMLHttpRequest|sendBeacon|WebSocket|https?:\/\//)});
check('safety boundaries retained in English source',()=>{const text=JSON.stringify(data.COURSE);for(const term of ['Do not force eye contact','Do not improvise','does not teach or authorise restraint','Do not investigate yourself','Do not wait for a diagnosis'])assert.ok(text.includes(term),term)});
console.log(`\n${count} focused content/build checks passed. These do not replace school review, human translation review or full browser testing.`);
