function validEmail(value){return typeof value==='string'&&!/[,:;"()\[\]\\]/.test(value)&&/^[^\s<>\r\n@]+@[^\s<>\r\n@]+\.[^\s<>\r\n@]+$/.test(value)&&value.length<=254}
function validProfile(){const p=state.profile||{};return Boolean(typeof p.name==='string'&&p.name.trim().length>=2&&p.name.length<=100&&typeof p.school==='string'&&p.school.trim().length>=2&&p.school.length<=150&&validEmail(p.email)&&validEmail(p.headEmail)&&p.headConfirmed===true)}
function responseReady(n){return typeof state.responses[n]==='string'&&typeof state.savedResponses[n]==='string'&&state.savedResponses[n].trim().length>=40&&state.savedResponses[n]===state.responses[n]}
function moduleReady(n){return state.moduleConfirmation[n]===true&&state.checked[n]===PRACTICE[n-1].a&&responseReady(n)}
function eligible(){return courseVersionMatches()&&state.version===VERSION&&validProfile()&&MODULE_IDS.every(n=>state.complete.includes(n)&&moduleReady(n))&&Boolean(state.attempts.at(-1)?.pass)&&declarations.every((_,i)=>state.ack[i])}
function ensureCertificate(){if(!eligible())return;const a=state.attempts.at(-1),p=state.profile,key=JSON.stringify([VERSION,p.name,p.email,p.school,p.headEmail,a.date]);const c=state.certificate;if(c?.key===key&&/^CR-ONLINE-1\.1-[A-F0-9]{8}$/.test(c.id)&&c.name===p.name&&c.school===p.school&&c.email===p.email&&c.score===a.score&&c.version===VERSION&&typeof c.date==='string'&&Number.isFinite(Date.parse(c.date)))return;state.certificate={key,id:'CR-ONLINE-'+VERSION+'-'+crypto.randomUUID().slice(0,8).toUpperCase(),name:p.name,school:p.school,email:p.email,date:new Date().toISOString(),score:a.score,version:VERSION};save()}
function profilePage(message=''){const p=state.profileDraft||{...state.profile,headEmailConfirm:state.profile.headConfirmed?state.profile.headEmail:'',confirmed:state.profile.headConfirmed};return `<div class="eyebrow">${tx('participantDetails')}</div><h1>${tx('recordTitle')}</h1><p class="lead">${tx('profileLead')}</p>${message?`<div class="notice">${esc(message)}</div>`:''}<form id="profile-form" class="paper" novalidate><div class="form-grid">${[['name','fullName','text',100,'name'],['email','emailField','email',254,'email'],['school','schoolField','text',150,'organization'],['headEmail','headEmailField','email',254,'off'],['headEmailConfirm','confirmHeadField','email',254,'off']].map(([name,label,type,max,autocomplete])=>`<label>${tx(label)}<input type="${type}" name="${name}" required ${type==='text'?'minlength="2"':''} maxlength="${max}" autocomplete="${autocomplete}" value="${esc(p[name]||'')}"></label>`).join('')}</div><label class="check-row"><input type="checkbox" name="confirmed" required ${p.confirmed?'checked':''}><span>${tx('confirmHead')}</span></label><p class="micro">${tx('profilePrivacy')}</p><p id="profile-error" class="error" role="alert"></p><button type="submit">${tx('saveDetails')}</button></form>`}
function readProfileForm(form){const fd=new FormData(form);return Object.fromEntries(['name','email','school','headEmail','headEmailConfirm'].map(k=>[k,String(fd.get(k)||'')]).concat([['confirmed',fd.get('confirmed')==='on']]))}
function bindCertificate(){const form=$('#profile-form');if(form){form.oninput=form.onchange=()=>{state.profileDraft=readProfileForm(form);save()};form.onsubmit=e=>{e.preventDefault();const draft=readProfileForm(form);state.profileDraft=draft;save();const p={name:draft.name.trim(),email:draft.email.trim(),school:draft.school.trim(),headEmail:draft.headEmail.trim(),headConfirmed:draft.confirmed};let error='';if(p.name.length<2||p.school.length<2)error='nameSchoolError';else if(p.name.length>100||p.school.length>150)error='profileLengthError';else if(!validEmail(p.email)||!validEmail(p.headEmail)||!validEmail(draft.headEmailConfirm.trim()))error='emailError';else if(p.headEmail.toLowerCase()!==draft.headEmailConfirm.trim().toLowerCase())error='emailMismatch';else if(!p.headConfirmed)error='headConfirmError';if(error){$('#profile-error').textContent=tr(error);return}state.profile=p;state.profileDraft=null;state.certificate=null;save();go(state.complete.length===6?'completion':'module-'+(MODULE_IDS.find(n=>!state.complete.includes(n))||1))}};
const button=$('#certificate-download');if(button)button.onclick=async()=>{const lang=state.language;button.disabled=true;button.textContent=tr('preparingPdf',{},lang);try{if(!eligible())throw Error(tr('requirementsError',{},lang));ensureCertificate();const bytes=await makeCertificatePDF(state.certificate,undefined,lang);saveBlob(new Blob([bytes],{type:'application/pdf'}),tr('certificateFilename',{},lang),'#certificate-status',tr('fileReady',{},lang),lang)}catch(e){notify(e.message||tr('pdfError',{},lang))}finally{button.disabled=false;button.textContent=tr('downloadCertificate',{},lang)}};
const email=$('#email-draft');if(email)email.onclick=async()=>{const lang=state.language;email.disabled=true;try{await downloadEmailDraft(lang)}catch(e){notify(tr('emailFileError',{},lang))}finally{email.disabled=false}}}
let certificateLogoPromise;
function certificateLogo(){if(typeof Image==='undefined')return Promise.resolve(null);if(!certificateLogoPromise)certificateLogoPromise=new Promise(resolve=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>resolve(null);img.src='assets/brand/inspired-logo-colour.png'});return certificateLogoPromise}
function drawCertificate(canvas,c,lang=state.language,logo=null,strings=null){canvas.width=1684;canvas.height=1190;const x=canvas.getContext('2d');x.fillStyle='#ffffff';x.fillRect(0,0,1684,1190);x.fillStyle='#122147';x.fillRect(0,0,1684,24);x.fillRect(0,1166,1684,24);x.strokeStyle='#1B75BB';x.lineWidth=3;x.strokeRect(45,50,1594,1090);x.textAlign='center';const t=(k,p={})=>certificateText(k,p,lang,strings);function text(value,y,size=26,colour='#143256',family='Open Sans, sans-serif'){x.font=`${size}px ${family}`;x.fillStyle=colour;x.fillText(value,842,y)}function fit(value,y,size,min=12,colour='#143256',family='Roboto, sans-serif'){while(size>min){x.font=`${size}px ${family}`;if(x.measureText(value).width<1450)break;size--}text(value,y,size,colour,family)}
if(logo)x.drawImage(logo,678,74,328,121);else text('INSPIRED EDUCATION',145,25);
fit(t('pdfStaff'),220,20,16,'#415165');fit(t('certificateTitle'),315,64);text(t('pdfConfirms'),373,25,'#415165');fit(c.name,461,60);x.strokeStyle='#1B75BB';x.lineWidth=1;x.beginPath();x.moveTo(450,495);x.lineTo(1234,495);x.stroke();fit(c.school,545,30);fit(t('pdfCompleted'),608,26,18,'#415165');fit(t('courseTitle'),678,46);fit(t('pdfSubtitle'),727,28);fit(t('pdfAssessment',{score:c.score,percent:c.score*5}),808,25);fit(t('pdfModules'),853,23);text(dateText(c.date,lang),916,25);fit(t('pdfReference',{id:c.id,version:c.version}),976,19,16,'#415165');fit(t('pdfDuration'),1028,19,16,'#415165');fit(t('pdfDisclaimer'),1062,18,15,'#415165');fit(t('pdfReview'),1093,18,14,'#415165');if(lang!=='en')fit(t('translationReviewShort'),1120,18,14,'#415165')}
function certificateText(key,params,lang,strings){if(!strings)return tr(key,params,lang);if(typeof strings[key]!=='string')throw Error('Missing version-specific certificate text: '+key);return strings[key].replace(/\{(\w+)\}/g,(_,name)=>String(params[name]??''))}
async function makeCertificatePDF(c,canvas,lang=state.language,strings=null){canvas=canvas||document.createElement('canvas');await document.fonts?.ready;const logo=await certificateLogo();drawCertificate(canvas,c,lang,logo,strings);const {PDFDocument}=window.PDFLib,doc=await PDFDocument.create();doc.setTitle(certificateText('courseTitle',{},lang,strings)+' - '+certificateText('certificateTitle',{},lang,strings));doc.setAuthor('Inspired Education');doc.setSubject(certificateText('pdfSubject',{},lang,strings));doc.setLanguage(locale(lang));const png=await doc.embedPng(canvas.toDataURL('image/png')),page=doc.addPage([842,595]);page.drawImage(png,{x:0,y:0,width:842,height:595});return doc.save()}
function base64Text(t){const bytes=new TextEncoder().encode(t);let s='';for(const byte of bytes)s+=String.fromCharCode(byte);return btoa(s)}
function wrap64(s){return s.match(/.{1,76}/g)?.join('\r\n')||''}
async function downloadEmailDraft(lang=state.language){if(!validProfile())throw Error(tr('participantDetailsError',{},lang));ensureCertificate();const p={...state.profile},c=eligible()?{...state.certificate}:null,report=reportText(lang),boundary='coregulation-'+crypto.randomUUID(),t=(k,params={})=>tr(k,params,lang),subject=t('emailSubject',{name:p.name}),filename=t('certificateFilename');const head=['X-Unsent: 1','To: '+p.headEmail,'Cc: '+p.email,'Reply-To: '+p.email,'Subject: =?UTF-8?B?'+base64Text(subject)+'?=','MIME-Version: 1.0','Content-Language: '+lang,'Content-Type: multipart/mixed; boundary="'+boundary+'"','','--'+boundary,'Content-Type: text/plain; charset=UTF-8','Content-Transfer-Encoding: base64','',wrap64(base64Text(t('emailGreeting')+'\n\n'+t('emailIntro')+'\n\n'+report))];if(c){const bytes=await makeCertificatePDF(c,undefined,lang);let bin='';for(const byte of bytes)bin+=String.fromCharCode(byte);head.push('--'+boundary,'Content-Type: application/pdf; name="'+filename+'"','Content-Disposition: attachment; filename="'+filename+'"','Content-Transfer-Encoding: base64','',wrap64(btoa(bin)))}head.push('--'+boundary+'--','');saveBlob(new Blob([head.join('\r\n')],{type:'message/rfc822'}),t('emailFilename'),'#report-status',t('emailReady'),lang)}
